### ISSUE TITLE
`RuntimeError` for longer sequences

### ISSUE THREAD

**Issue by menoliu** [THGLab/int2cart#5]
Issue does not occur for shorter sequences such as drkN SH3 but becomes increasingly problematic for sequences >100 residues. On clusters, this type of error results in a `core dump`.

Sample:
```
  File "/home/nemoliu/IDPConformerGenerator/src/idpconfgen/components/bgeo_strategies/int2cart/bgeo_int2cart.py", line 53, in get_internal_coords
    units="radian",
  File "/home/nemoliu/IDPConformerGenerator/int2cart/modelling/utils/predict.py", line 41, in predict
    predictions = builder.predictor(model_inputs)
  File "/home/nemoliu/anaconda3/envs/idpconfgen/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nemoliu/IDPConformerGenerator/int2cart/modelling/models/multihead.py", line 19, in forward
    latent = self.encoder(inputs)
  File "/home/nemoliu/anaconda3/envs/idpconfgen/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nemoliu/IDPConformerGenerator/int2cart/modelling/models/rnn.py", line 831, in forward
    x = torch.cat(filtered_inputs, dim=2)
RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 2 but got size 1 for tensor number 3 in the list.
```

[build_rpr_on_crash_sic1.txt](https://github.com/THGLab/int2cart/files/8774238/build_rpr_on_crash_sic1.txt)

**Comment by menoliu** [comment]
@JerryJohnsonLee As I'm testing this more on local machines, it seems like an issue for shorter sequences like drk as well... I'm wondering what are the consequences of changing `dim=2` to `dim=1`? Would that effect how `int2cart` will run outside the integration? I will fork and test

**Comment by JerryJohnsonLee** [comment]
Hi Nemo, thanks for digging deep into this issue. The second axis of this array should corresponds to the length of the input sequence, so what you show here is a mismatch of sequence length for the amino acid sequence and the torsion angles (amino acid of length 1, torsion angles of length 2). Can you check what are the inputs to this forward call?

**Comment by menoliu** [comment]
Thanks for looking into this Jerry! What's interesting about this bug is that it only occasionally occurs... I've noticed with a larger backbone energy limit (e.g. `-etbb 10000`) this occurs less frequently. Here is my test command:

`idpconfgen build --bgeo-strategy int2cart -seq GSMTPSTPPRSRGTRYLAQPSGNTSSSALMQGQKTPQKPSQNLVPVTPSTTKSFKNAPLLAPPNSNMGMTSPFNGLTSPQRSPFPKSSVKRT -db ../database/idpconfgen_database_rd.json -etbb 100 -et 'pairs'  -dsd -of ./sic1L+_forward_100pairs -nc 100 -n 50`

Here's the inputs for the `forward(self, inputs)`:
```
# for 'self'
RecurrentModel(
  (angle_smearing): GaussianSmearing()
  (residue_embedding): Embedding(20, 64)
  (filters): ModuleList(
    (0): MLP(
      (dense_layers): ModuleList(
        (0): Dense(
          in_features=180, out_features=90, bias=True
          (activation): ReLU()
        )
        (1): Dense(in_features=90, out_features=64, bias=True)
      )
    )
    (1): MLP(
      (dense_layers): ModuleList(
        (0): Dense(
          in_features=180, out_features=90, bias=True
          (activation): ReLU()
        )
        (1): Dense(in_features=90, out_features=64, bias=True)
      )
    )
    (2): MLP(
      (dense_layers): ModuleList(
        (0): Dense(
          in_features=180, out_features=90, bias=True
          (activation): ReLU()
        )
        (1): Dense(in_features=90, out_features=64, bias=True)
      )
    )
  )
  (mixing_filter): MLP(
    (dense_layers): ModuleList(
      (0): Dense(
        in_features=256, out_features=128, bias=True
        (activation): ReLU()
      )
      (1): Dense(in_features=128, out_features=64, bias=True)
    )
  )
  (recurrent): GRU(64, 100, num_layers=3, dropout=0.1, bidirectional=True)
)

# for 'inputs'
{'phi': tensor([[ 1.5639, -1.5610]]), 'psi': tensor([[-0.0367, -2.3074]]), 'omega': tensor([[3.0766, 2.9335]]), 'res_type': tensor([[5]]), 'lengths': [1]}
```

**Comment by JerryJohnsonLee** [comment]
@menoliu Could you check when this error happens, whether in IDPCG (https://github.com/julie-forman-kay-lab/IDPConformerGenerator/blob/main/src/idpconfgen/cli_build.py#L1152) seqs and tors have matching length? seq should be length L, tors should be Lx3. I suspect there might be a mismatch of length there. If that is the case, we should raise an issue in the IDPCG repo.

**Comment by menoliu** [comment]
Great catch @JerryJohnsonLee ! I've tried that and it works so far. I have implemented a `raise ValueError` when that occurs in IDPCG, and will PR the solution there. Time to do more benchmarks with this bug fixed :)

Cheers, I'm closing this issue now.
